dining = [
    {
        name: "Jacobo 4 Seater Dining Set in Charcoal Colour",
        subtype: "Contemporary 4 Seater Dining Sets",
        image1: "https://ii2.pepperfry.com/media/catalog/product/j/a/494x544/jacobo-4-seater-dining-set-in-charcoal-colour-by-casacraft-jacobo-4-seater-dining-set-in-charcoal-co-2c8hhv.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/j/a/800x880/jacobo-4-seater-dining-set-in-charcoal-colour-by-casacraft-jacobo-4-seater-dining-set-in-charcoal-co-mebco3.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/j/a/70x77/jacobo-4-seater-dining-set-in-charcoal-colour-by-casacraft-jacobo-4-seater-dining-set-in-charcoal-co-fkvtj0.jpg",
        price:  " 97999",
        brand: " CasaCraft",
        discount: "51571",
        discount_price:"46428",
    },
    {
        name: "Vicente 4 Seater Dining Set in Charcoal Colour",
        subtype:"Contemporary 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/v/i/800x880/vicente-4-seater-dining-set-in-charcoal-colour-by-casacraft-vicente-4-seater-dining-set-in-charcoal--o1x2pm.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/v/i/800x880/vicente-4-seater-dining-set-in-charcoal-colour-by-casacraft-vicente-4-seater-dining-set-in-charcoal--slgy6d.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii1.pepperfry.com/media/catalog/product/v/i/800x880/vicente-4-seater-dining-set-in-charcoal-colour-by-casacraft-vicente-4-seater-dining-set-in-charcoal--g4aodo.jpg",
        price: "97999",
        brand: "CasaCraft",
        discount: "61294",
        discount_price :"36705",
    },
    {
        name: "Abbey Solid Wood 4 Seater Dining Set In Honey Oak Finish",
        subtype:"Contemporary 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/a/b/800x880/abbey-solid-wood-four-seater-dining-set-in-honey-oak-finish-by-woodsworth-abbey-solid-wood-four-seat-psevp6.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/a/b/800x880/abbey-solid-wood-four-seater-dining-set-in-honey-oak-finish-by-woodsworth-abbey-solid-wood-four-seat-b3go6z.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/a/b/70x77/abbey-solid-wood-four-seater-dining-set-in-honey-oak-finish-by-woodsworth-abbey-solid-wood-four-seat-57qdie.jpg",
        price: "76999",
        brand: "Woodsworth",
        discount: "30000",
        discount_price:"46999",
    },
    {
        name: "Flair Solid Wood 4 Seater Dining Set In Provincial Teak Finish",
        subtype:"Contemporary 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/f/l/800x880/flair-solid-wood-4-seater-dining-set-in-provincial-teak-finish-by-woodsworth-flair-solid-wood-4-seat-ngr8cm.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/f/l/800x880/flair-solid-wood-4-seater-dining-set-in-provincial-teak-finish-by-woodsworth-flair-solid-wood-4-seat-x2ggb9.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/f/l/70x77/flair-solid-wood-4-seater-dining-set-in-provincial-teak-finish-by-woodsworth-flair-solid-wood-4-seat-yhpcmk.jpg",
        price: "86999",
        brand:"Woodsworth",
        discount: "36857",
        discount_price:"50142",
    },
    {
        name: "Knot 4 Seater Dining Table in Wenge Colour",
        subtype:"Contemporary 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/k/n/800x880/knot-4-seater-dining-table-in-wenge-colour-by-eros-knot-4-seater-dining-table-in-wenge-colour-by-ero-ercjn0.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/k/n/800x880/knot-4-seater-dining-table-in-wenge-colour-by-eros-knot-4-seater-dining-table-in-wenge-colour-by-ero-mgcgcw.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/k/n/70x77/knot-4-seater-dining-table-in-wenge-colour-by-eros-knot-4-seater-dining-table-in-wenge-colour-by-ero-kxg0yg.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/k/n/800x880/knot-4-seater-dining-table-in-wenge-colour-by-eros-knot-4-seater-dining-table-in-wenge-colour-by-ero-wlzeu0.jpg",
        price: "37999",
        brand: "Eros",
        discount: "5509",
        discount_price :"32490",
    },
    {
        name:"Cheyanne 4 Seater Dining Set in Walnut Finish",
        subtype: "Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/c/h/800x880/cheyanne-4-seater-dining-table-in-walnut-finish---mintwud-by-pepperfry-cheyanne-4-seater-dining-tabl-y8o3sq.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/c/h/800x880/cheyanne-4-seater-dining-table-in-walnut-finish---mintwud-by-pepperfry-cheyanne-4-seater-dining-tabl-iiirns.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/e/u/70x77/europa-4-seater-square-dining-set-in-walnut-colour-by--home-europa-4-seater-square-dining-set-in-wal-x6pow4.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/e/u/70x77/europa-4-seater-square-dining-set-in-walnut-colour-by--home-europa-4-seater-square-dining-set-in-wal-2zh1mk.jpg",
        price: "45999",
        brand:"Mintwud",
        discount: "26000",
        discount_price: "19999",
    },
    {
        name: "Mariko 4 Seater Dining Set in Wenge Finish",
        subtype: "Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/m/a/800x880/mariko-4-seater-dining-set-in-wenge-finish---mintwud-by-pepperfry-mariko-4-seater-dining-set-in-weng-ogz64j.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/m/a/800x880/mariko-4-seater-dining-set-in-wenge-finish---mintwud-by-pepperfry-mariko-4-seater-dining-set-in-weng-cu96ek.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/m/a/70x77/mariko-four-seater-dining-set-in-wenge-finish-by-mintwud-mariko-four-seater-dining-set-in-wenge-fini-ouiasf.jpg",
        price: "48177",
        brand: "Mintwud",
        discount: "32178",
        discount_price: "15999",
    },
    {
        name: "Chinami 4 Seater Dining Set with Bench in Dark Cappucino Brown Finish",
        subtype: "Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/c/h/800x880/chinami-4-seater-dining-set-with-bench-in-dark-cappucino-brown-finish---valuewud-chinami-4-seater-di-gqo9sb.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/c/h/800x880/chinami-4-seater-dining-set-with-bench-in-dark-cappucino-brown-finish---valuewud-chinami-4-seater-di-iglv2p.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/m/a/70x77/mariko-four-seater-dining-set-in-wenge-finish-by-mintwud-mariko-four-seater-dining-set-in-wenge-fini-ouiasf.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/c/h/70x77/chinami-4-seater-dining-set-with-bench-in-dark-cappuccino-finish---valuewud-chinami-4-seater-dining--sbbmi9.jpg",
        price: "34999",
        brand: "ValueWud",
        discount: "15431",
        discount_price :"19568",
    },
    {
        name: "Biscay Solid Wood 4 Seater Dining Set Rectangle In Rustic Teak Finish",
        subtype: "Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/b/i/800x880/biscay-solid-wood-4-seater-dining-set-rectangle-in-rustic-teak-finish---woodsworth-by-pepperfry-bisc-ythcu9.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/b/i/800x880/biscay-solid-wood-4-seater-dining-set-rectangle-in-rustic-teak-finish---woodsworth-by-pepperfry-bisc-elwksa.jpg",
        price: "64999",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/b/i/70x77/biscay-solid-wood-dining-set-in-rustic-teak-finish---woodsworth-by-pepperfry-biscay-solid-wood-dinin-pe5e2x.jpg",
        brand: "Woodsworth",
        discount: "27393",
        discount_price : "37606",
    },
    {
        name:"Segur Solid Wood 4 Seater Dining Set In Provincial Teak Finish",
        subtype: "Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/s/e/800x880/segur-solid-wood-4-seater-dining-set-in-provincial-teak-finish-by-woodsworth-segur-solid-wood-4-seat-vqg4y2.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/s/e/800x880/segur-solid-wood-4-seater-dining-set-in-provincial-teak-finish-by-woodsworth-segur-solid-wood-4-seat-30vgsn.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/s/e/70x77/segur-solid-wood-4-seater-dining-set-in-provincial-teak-finish-by-woodsworth-segur-solid-wood-4-seat-sxk4fg.jpg",
        price: "72999",
        brand: "Woodsworth",
        discount: "28000",
        discount_price:"44999",
    },
    {
        name: "Hachiro 4 Seater Dining Set in Walnut & Dark Brown Finish",
        subtype:"Mid-Century Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/h/a/800x880/hachiro-4-seater-dining-set-in-walnut---dark-brown-finish-by-casacraft-hachiro-4-seater-dining-set-i-spfxig.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/h/a/800x880/hachiro-4-seater-dining-set-in-walnut---dark-brown-finish-by-casacraft-hachiro-4-seater-dining-set-i-k8k9lw.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/h/a/70x77/hachiro-4-seater-dining-set-in-walnut---dark-brown-finish-by-casacraft-hachiro-4-seater-dining-set-i-zwuddu.jpg",
        price: "85999",
        brand: "CasaCraft",
        discount: "36000",
        discount_price: "49999",
    },
    {
            name: "Fumio 4 Seater Dining Set in Walnut & Beige Finish",
            subtype:"Mid-Century Modern 4 Seater Dining Sets",
            image1: "https://ii1.pepperfry.com/media/catalog/product/f/u/800x880/fumio-4-seater-dining-set-in-walnut---beige-finish-by-casacraft-fumio-4-seater-dining-set-in-walnut--fv06wf.jpg",
            image2: "https://ii1.pepperfry.com/media/catalog/product/f/u/800x880/fumio-4-seater-dining-set-in-walnut---beige-finish-by-casacraft-fumio-4-seater-dining-set-in-walnut--mntczt.jpg",
            image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
            image4: "https://ii3.pepperfry.com/media/catalog/product/f/u/70x77/fumio-4-seater-dining-set-in-walnut---beige-finish-by-casacraft-fumio-4-seater-dining-set-in-walnut--z8gz39.jpg",
            price: "39999",
            brand: "CasaCraft",
            discount: "17714",
            discount_price:"22285",
        },
        {
        name: "Jenna 4 Seater Dining Set In Black",
        subtype:"Mid-Century Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/j/e/800x880/jenna-dining-set-in-black-by-durian-jenna-dining-set-in-black-by-durian-hepwa1.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/j/e/800x880/jenna-dining-set-in-black-by-durian-jenna-dining-set-in-black-by-durian-dbobjd.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/j/e/70x77/jenna-dining-set-in-black-by-durian-jenna-dining-set-in-black-by-durian-dafujp.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/j/e/70x77/jenna-dining-set-in-black-by-durian-jenna-dining-set-in-black-by-durian-oxenhk.jpg",
        price: "44200",
        brand: "Durian",
        discount: "19006",
        discount_price:"25194",
    },
     
    {
        name: "Corona 4 Seater Dining Set in White Colour",
        subtype:"Mid-Century Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/c/o/800x880/corona-4-seater-dining-set-in-white-colour-by-hometown-corona-4-seater-dining-set-in-white-colour-by-myknvo.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/c/o/800x880/corona-4-seater-dining-set-in-white-colour-by-hometown-corona-4-seater-dining-set-in-white-colour-by-myknvo.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/c/o/70x77/corona-four-seater-metal-dining-set-in-white-colour-by-hometown-corona-four-seater-metal-dining-set--6kresg.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/c/o/70x77/corona-four-seater-metal-dining-set-in-white-colour-by-hometown-corona-four-seater-metal-dining-set--lfymbu.jpg",
        price: "39900",
        brand: "HomeTown",
        discount: "25651",
        discount_price :"14249",
    },
    {
        name:"Barcelona 4 Seater Dining Set In American Walnut Finish",
        subtype:"Mid-Century Modern 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/b/a/800x880/barcelona-4-seater-dining-set-in-american-walnut-finish-by-orange-tree-barcelona-4-seater-dining-set-lgk7a7.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/b/a/800x880/barcelona-4-seater-dining-set-in-american-walnut-finish-by-orange-tree-barcelona-4-seater-dining-set-icj8mk.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/b/a/70x77/barcelona-4-seater-dining-set-in-american-walnut-finish-by-orange-tree-barcelona-4-seater-dining-set-9pwhcs.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/b/a/70x77/barcelona-4-seater-dining-set-in-american-walnut-finish-by-orange-tree-barcelona-4-seater-dining-set-3au2az.jpg",
        price: "71900",
        brand: "Orange Tree",
        discount: "3595",
        discount_price:"68305",
    },
    {
        name: "Nuevo Solid Wood 4 Seater Dining Set In Rustic Teak Finish",
        subtype: "Transitional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/n/u/800x880/nuevo-solid-wood-4-seater-dining-set-in-rustic-teak-finish---woodsworth-by-pepperfry-nuevo-solid-woo-hoxpc2.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/n/u/800x880/nuevo-solid-wood-4-seater-dining-set-in-rustic-teak-finish-by-woodsworth-nuevo-solid-wood-4-seater-d-s2neq1.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/n/u/70x77/nuevo-solid-wood-4-seater-dining-set-in-rustic-teak-finish-by-woodsworth-nuevo-solid-wood-4-seater-d-hmu27q.jpg",
        price: "62999",
        brand: "Woodsworth",
        discount: "27250",
        discount_price :"35749",
    },
    {
        name:"Taarkashi 4 Seater Dining Set In Teak Finish",
        subtype:"Transitional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/t/a/800x880/taarkashi-four-seater-dining-set-taarkashi-four-seater-dining-set-w6kpbp.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/t/a/800x880/taarkashi-four-seater-dining-set-taarkashi-four-seater-dining-set-xlwdab.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/t/a/70x77/taarkashi-four-seater-dining-set-taarkashi-four-seater-dining-set-yxmzv5.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/t/a/70x77/taarkashi-four-seater-dining-set-taarkashi-four-seater-dining-set-e1dxbl.jpg",
        price: "132965",
        brand: "Fabuliv",
        discount: "65165",
        discount_price :"67800",
    },
    {
        name: "Parnika Solid Wood 4 Seater Dining Set With Bench In Honey Oak Finish",
        subtype:"Transitional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/p/a/800x880/parnika-solid-wood-4-seater-dining-set-with-bench-in-honey-oak-finish---mudramark-by-pepperfry-parni-z7aelw.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/p/a/800x880/parnika-solid-wood-4-seater-dining-set-with-bench-in-honey-oak-finish--mudramark-by-pepperfry-parnik-lwkeop.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/p/a/70x77/parnika-solid-wood-4-seater-dining-set-with-bench-in-honey-oak-finish--mudramark-by-pepperfry-parnik-pyekjv.jpg",
        price: "72999",
        brand: "Mudramark",
        discount: "28000",
        discount_price:"44999",
    },
    {
        name:"Artois 4 Seater Dining Set in Dark Walnut Finish",
        subtype:"Transitional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/a/r/800x880/artois-4-seater-dining-set-in-dark-walnut-finish-by-hometown-artois-4-seater-dining-set-in-dark-waln-3j3xyf.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/a/r/800x880/artois-four-seater-dining-set-with-bench---two-chairs-in-dark-walnut-finish-by-hometown-artois-four--tdfgk7.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/a/r/70x77/artois-four-seater-dining-set-with-bench---two-chairs-in-dark-walnut-finish-by-hometown-artois-four--yck9sp.jpg",
        price: "36300",
        brand: "HomeTown",
        discount: "19201",
        discount_price :"17099",
    },
    {
        name: "Drusilla Solid Wood 4 Seater Dining Set With Chair In Provincial Teak Finish",
        subtype:"Transitional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/d/r/800x880/drusilla-solid-wood-4-seater-dining-set-with-chair-in-provincial-teak-finish---by-woodsworth-drusill-jlwkdp.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/d/r/800x880/drusilla-solid-wood-4-seater-dining-set-with-chair-in-provincial-teak-finish---by-woodsworth-drusill-rdkrgy.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/d/r/70x77/drusilla-solid-wood-4-seater-dining--table-in-provincial-teak-finish---by-woodsworth-drusilla-solid--f3whpz.jpg",
        image4: "https://ii3.pepperfry.com/media/catalog/product/d/r/70x77/drusilla-solid-wood-4-seater-dining--table-in-provincial-teak-finish---by-woodsworth-drusilla-solid--f3whpz.jpg",
        price: "74999",
        brand: "Woodsworth",
        discount: "29000",
        discount_price : "45999",
    },
    {
        name: "Anne Solid Wood Four Seater Dining Set in Warm Chestnut Finish",
        subtype:"Traditional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/a/n/800x880/anne-solid-wood-four-seater-dining-set-in-warm-chestnut-finish-by-amberville-anne-solid-wood-four-se-rwd2fq.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/a/n/800x880/anne-solid-wood-four-seater-dining-set-in-warm-chestnut-finish-by-amberville-anne-solid-wood-four-se-h9tj44.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/a/n/70x77/anne-solid-wood-four-seater-dining-set-in-warm-chestnut-finish-by-amberville-anne-solid-wood-four-se-vdyjh2.jpg",
        price: "109199",
        brand: "Amberville",
        discount: "53950",
        discount_price:"55249",
    },
    {
        name: "Inaaya Solid Wood 4 Seater Dining Set In Dark Mahogany Finish",
        subtype:"Traditional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/k/r/800x880/krisa-solid-wood-4-seater-dining-set-in-dark-mahogany-finish---mudramark-by-pepperfry-krisa-solid-wo-aa7obd.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/k/r/800x880/krisa-solid-wood-4-seater-dining-set-in-dark-mahogany-finish---mudramark-by-pepperfry-krisa-solid-wo-fiw4d6.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/a/n/70x77/anne-solid-wood-four-seater-dining-set-in-warm-chestnut-finish-by-amberville-anne-solid-wood-four-se-vdyjh2.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/k/r/70x77/krisa-solid-wood-4-seater-dining-set-in-dark-mahogany-finish---mudramark-by-pepperfry-krisa-solid-wo-qosteb.jpg",
        price: "88999",
        brand: "Mudramark",
        discount: "38393",
        discount_price :"50606",
    },
    {
        name:"Stanfield Solid Wood 4 Seater Dining Set In Provincial Teak Finish",
        subtype:"Traditional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/s/t/800x880/stanfield-solid-wood-4-seater-dining-set-in-provincial-teak-finish-by-amberville-stanfield-solid-woo-2tn1tw.jpg",
        image2:"https://ii1.pepperfry.com/media/catalog/product/s/t/800x880/stanfield-solid-wood-4-seater-dining-set-in-provincial-teak-finish-by-amberville-stanfield-solid-woo-sryyts.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/s/t/70x77/stanfield-solid-wood-four-seater-dining-set-in-provincial-teak-finish-by-amberville-stanfield-solid--p8pgfi.jpg",
        price: "67999",
        brand: "Amberville",
        discount: "29000",
        discount_price : "38999",
        },
    {
        name: "Chippa Solid Wood 4 Seater Dining Set In Tubbaq Finish",
        subtype:"Traditional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/c/h/800x880/chippa-solid-wood-4-seater-dining-table-set-in-tubbaq-finish---mudramark-by-pepperfry-chippa-solid-w-trbuxt.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/c/h/800x880/chippa-solid-wood-4-seater-dining-table-set-in-tubbaq-finish---mudramark-by-pepperfry-chippa-solid-w-0bslck.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/c/h/70x77/chippa-solid-wood-4-seater-dining-table-set-in-tubbaq-finish---mudramark-by-pepperfry-chippa-solid-w-koj3kc.jpg",
        price: "74999",
        brand: "Mudramark",
        discount: "28500",
        discount_price :"46499",
    },
    {
        name: "Alabaster Solid Wood Four Seater Dining Set In Ivory Finish",
        subtype:"Traditional 4 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/a/l/800x880/alabaster-solid-wood-four-seater-dining-set-in-ivory-finish---mudramark-by-pepperfry-alabaster-solid-yk2ucj.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/a/l/800x880/alabaster-solid-wood-four-seater-dining-set-in-ivory-finish---mudramark-by-pepperfry-alabaster-solid-yk2ucj.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/a/l/70x77/alabaster-solid-wood-four-seater-dining-set-in-ivory-finish---mudramark-by-pepperfry-alabaster-solid-wz2phc.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/a/l/70x77/alabaster-solid-wood-four-seater-dining-set-in-ivory-finish---mudramark-by-pepperfry-alabaster-solid-hugosz.jpg",
        price: "78999",
        brand: "Mudramark",
        discount: "30500",
        discount_price :"48499",
    },
    {
        name: "Cheyanne 6 Seater Dining Set in Walnut Finish",
        subtype: "Modern 6 Seater Dining Sets",
        image1:  "https://ii1.pepperfry.com/media/catalog/product/c/h/800x880/cheyanne-6-seater-dining-table-in-walnut-finish---mintwud-by-pepperfry-cheyanne-6-seater-dining-tabl-4iqmtm.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/c/h/800x880/cheyanne-6-seater-dining-table-in-walnut-finish---mintwud-by-pepperfry-cheyanne-6-seater-dining-tabl-dt96vj.jpg",
        image3: "https://ii1.pepperfry.com/media/catalog/product/a/l/70x77/alabaster-solid-wood-four-seater-dining-set-in-ivory-finish---mudramark-by-pepperfry-alabaster-solid-hugosz.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/a/l/70x77/alabaster-solid-wood-four-seater-dining-set-in-ivory-finish---mudramark-by-pepperfry-alabaster-solid-hugosz.jpg",
        price: "65999",
        brand: "Mintwud",
        discount: "39000",
        discount_price : "26999",
    },
    {
        name: "Fabiola 6 Seater Dining Set in Walnut Finish",
        subtype: "Modern 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/f/a/800x880/fabiola-6-seater-dining-table-in-walnut-finish---mintwud-by-pepperfry-fabiola-6-seater-dining-table--tefcwy.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/f/a/800x880/fabiola-6-seater-dining-table-in-walnut-finish---mintwud-by-pepperfry-fabiola-6-seater-dining-table--yc4akc.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/f/a/70x77/fabiola-6-seater-dining-table-in-walnut-finish---mintwud-by-pepperfry-fabiola-6-seater-dining-table--2b6aeb.jpg",
        price: "63999",
        brand: "Mintwud",
        discount: "41000",
        discount_price: "22999",
    },
    {
        name: "Gilliane Solid Wood 6 Seater Dining Set In Provincial Teak Finish",
        subtype: "Modern 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/g/i/800x880/gilliane-solid-wood-dining-set-in-provincial-teak-finish---woodsworth-by-pepperfry-gilliane-solid-wo-lb4vmk.jpg",
        image2:  "https://ii1.pepperfry.com/media/catalog/product/g/i/800x880/gilliane-solid-wood-dining-set-in-provincial-teak-finish---woodsworth-by-pepperfry-gilliane-solid-wo-dwfctd.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/g/i/70x77/gilliane-solid-wood-dining-set-in-provincial-teak-finish---woodsworth-by-pepperfry-gilliane-solid-wo-vkcxv9.jpg",
        price: "121999",
        brand: "Woodsworth",
        discount: "52357",
        discount_price : "69642",
    },
    {
        name: "Enkel Solid Wood 6 Seater Dining Set In Warm Chestnut Finish",
        subtype: "Modern 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/e/n/800x880/enkel-solid-wood-6-seater-dining-set-in-warm-chestnut-finish-by-woodsworth-enkel-solid-wood-6-seater-wdtgn6.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/e/n/800x880/enkel-solid-wood-six-seater-dining-set-in-warm-chestnut-finish-by-woodsworth-enkel-solid-wood-six-se-o2clix.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/e/n/70x77/enkel-solid-wood-six-seater-dining-set-in-warm-chestnut-finish-by-woodsworth-enkel-solid-wood-six-se-ifjma2.jpg",
        price: " 109999",
        brand: "Woodsworth",
        discount: "46857",
        discount_price : "63142",
    },
    {
        name: "Rezzan Solid Wood 6 Seater Dining Set In Rustic Teak Finish",
        subtype: "Modern 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/r/e/800x880/rezzan-solid-wood-6-seater-dining-set-in-rustic-teak-finish---woodsworth-by-pepperfry-rezzan-solid-w-0jynoc.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/r/e/800x880/rezzan-solid-wood-6-seater-dining-set-in-rustic-teak-finish---woodsworth-by-pepperfry-rezzan-solid-w-0jynoc.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/r/e/70x77/rezzan-solid-wood-6-seater-dining-set-in-rustic-teak-finish---woodsworth-by-pepperfry-rezzan-solid-w-8pl8o1.jpg",
        price: "103999",
        brand: "Woodsworth",
        discount: "44571",
        discount_price : "59428",
    },
    {
        name: "Haruka 6 Seater Dining Set in Walnut & Sky Blue Finish",
        subtype: "Mid-Century Modern 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/h/a/800x880/haruka-6-seater-dining-set-in-walnut---sky-blue-finish-by-casacraft-haruka-6-seater-dining-set-in-wa-9vbvhl.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/h/a/800x880/haruka-6-seater-dining-set-in-walnut---sky-blue-finish-by-casacraft-haruka-6-seater-dining-set-in-wa-qafayk.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/h/a/70x77/haruka-6-seater-dining-set-in-walnut---sky-blue-finish-by-casacraft-haruka-6-seater-dining-set-in-wa-0bhoxf.jpg",
        price: " 137999",
        brand: "CasaCraft",
        discount: "63714",
        discount_price : "74285",
    },
    {
        name: "Creo Six Seater Dining set in Grey / White Colour",
        subtype: "Mid-Century Modern 6 Seater Dining Sets",
        image1:"https://ii1.pepperfry.com/media/catalog/product/c/r/800x880/creo-six-seater-dining-set-in-grey---white-colour-by-berrak-creo-six-seater-dining-set-in-grey---whi-jikzze.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/c/r/800x880/creo-six-seater-dining-set-in-grey---white-colour-by-berrak-creo-six-seater-dining-set-in-grey---whi-ihnnt2.jpg",
        image3: "https://ii3.pepperfry.com/media/catalog/product/c/r/70x77/creo-six-seater-dining-set-in-grey---white-colour-by-berrak-creo-six-seater-dining-set-in-grey---whi-rjrzby.jpg",
        image4: "https://ii1.pepperfry.com/media/catalog/product/c/r/70x77/creo-six-seater-dining-set-in-grey---white-colour-by-berrak-creo-six-seater-dining-set-in-grey---whi-jaxbnl.jpg",
        price: "155000",
        brand: "Berrak",
        discount: "37200",
        discount_price :"117800",
    },
    {
        name:"Issac 6 Seater Dining Set in Black Colour",
        subtype:"Mid-Century Modern 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/i/s/800x880/issac-6-seater-dining-set-in-black-colour-by--home-issac-6-seater-dining-set-in-black-colour-by--hom-hcf6us.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/i/s/800x880/issac-6-seater-dining-set-in-black-colour-by--home-issac-6-seater-dining-set-in-black-colour-by--hom-ihrqwf.jpg",
        image3: "https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4: "https://ii3.pepperfry.com/media/catalog/product/i/s/70x77/issac-6-seater-dining-set-in-black-colour-by--home-issac-6-seater-dining-set-in-black-colour-by--hom-g0dv25.jpg",
        price: "38500",
        brand: "@home",
        discount: "11600",
        discount_price:"26900",
    },
    {
        name: "Noir Novelty 6 Seater Dining Table Set with Bench in Blue Colour",
        subtype:"Mid-Century Modern 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/n/o/800x880/noir-novelty--6-seater-dining-table-set-with-bench-in-blue-colour-by-home-centre-noir-novelty--6-sea-vzpk6m.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/n/o/800x880/noir-novelty--6-seater-dining-table-set-with-bench-in-blue-colour-by-home-centre-noir-novelty--6-sea-vzpk6m.jpg",
        image3:"https://ii1.pepperfry.com/media/catalog/product/n/o/800x880/noir-novelty--6-seater-dining-table-set-with-bench-in-blue-colour-by-home-centre-noir-novelty--6-sea-lxpylf.jpg",
        image4:"https://ii1.pepperfry.com/media/catalog/product/n/o/800x880/noir-novelty--6-seater-dining-table-set-with-bench-in-blue-colour-by-home-centre-noir-novelty--6-sea-yf64jx.jpg",
        price: "88713",
        brand:"Home Centre",
        discount:"13307",
        discount_price :"75406",
    },
    {
        name:  "Jenna 6 Seater Dining Set in Black Finish",
        subtype:"Mid-Century Modern 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/j/e/800x880/jenna-6-seater-dining-set-in-black-finish-by-durian-jenna-6-seater-dining-set-in-black-finish-by-dur-y3cbwx.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/j/e/800x880/jenna-6-seater-dining-set-in-black-finish-by-durian-jenna-6-seater-dining-set-in-black-finish-by-dur-y3cbwx.jpg",
        image3:"https://ii1.pepperfry.com/media/catalog/product/j/e/800x880/jenna-6-seater-dining-set-in-black-finish-by-durian-jenna-6-seater-dining-set-in-black-finish-by-dur-yytkip.jpg",
        image4:"https://ii1.pepperfry.com/media/catalog/product/j/e/800x880/jenna-6-seater-dining-set-in-black-finish-by-durian-jenna-6-seater-dining-set-in-black-finish-by-dur-yytkip.jpg",
        price: "69000",
        brand:"Durian",
        discount:"29670",
        discount_price:"39330",
    },
    {
        name: "Segur Solid Wood 8 Seater Dining Set In Provincial Teak Finish",
        subtype: "Modern 8 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/s/e/800x880/segur-solid-wood-8-seater-dining-set-in-provincial-teak-finish-by-woodsworth-segur-solid-wood-8-seat-sx1meq.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/s/e/800x880/segur-solid-wood-8-seater-dining-set-in-provincial-teak-finish-by-woodsworth-segur-solid-wood-8-seat-sx1meq.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/s/e/800x880/segur-solid-wood-8-seater-dining-set-in-provincial-teak-finish-by-woodsworth-segur-solid-wood-8-seat-1afsd2.jpg",
        price: " 123999",
        brand:"Woodsworth",
        discount:"52964",
        discount_price :"71035",
    },
    {
        name: "Acropolis Solid Wood 8 Seater Dining Set In Provincial Teak Finish",
        subtype: "Modern 8 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/a/c/800x880/acropolis-solid-wood-eight-seater-dining-set-in-provincial-teak-finish-by-woodsworth-acropolis-solid-dxt1w2.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/a/c/800x880/acropolis-solid-wood-eight-seater-dining-set-in-provincial-teak-finish-by-woodsworth-acropolis-solid-jodoip.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/a/c/800x880/acropolis-solid-wood-8-seater-dining-set-in-provincial-teak-finish-by-woodsworth-acropolis-solid-woo-srgoaz.jpg",
        price: " 122999",
        brand:"Woodsworth",
        discount:"52429",
        discount_price :"70570",
    },
    {
        name: "Contemporary 8 Seater Dining Sets",
        subtype: "Modern 8 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/r/e/800x880/rezzan-solid-wood-8-seater-dining-set-in-rustic-teak-finish---woodsworth-by-pepperfry-rezzan-solid-w-is0nzt.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/r/e/800x880/rezzan-solid-wood-8-seater-dining-set-in-rustic-teak-finish---woodsworth-by-pepperfry-rezzan-solid-w-is0nzt.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/r/e/800x880/rezzan-solid-wood-8-seater-dining-set-in-rustic-teak-finish---woodsworth-by-pepperfry-rezzan-solid-w-jmx9nk.jpg",
        price: "130999",
        brand:"Woodsworth",
        discount:"55786",
        discount_price :"75213",
    },
    {
        name: "Live-Edge Solid Wood 8 Seater Dining Set In Natural Acacia Finish",
        subtype: "Modern 8 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/l/i/800x880/live-edge-solid-wood-8-seater-dining-set-in-natural-acacia-finish-by-woodsworth-live-edge-solid-wood-ythngn.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/l/i/800x880/live-edge-solid-wood-8-seater-dining-set-in-natural-acacia-finish-by-woodsworth-live-edge-solid-wood-48asot.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/l/i/800x880/live-edge-solid-wood-8-seater-dining-set-with-2-benches-in-natural-acacia-finish-by-woodsworth-live--i04udt.jpg",
        price: "185999",
        brand:"Woodsworth",
        discount:"79679",
        discount_price :"106320",
    },
    {
        name: "Catherine 8 Seater Marble Top Dining Set in Off White & Brown Colour",
        subtype: "Modern 8 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/c/a/800x880/catherine-8-seater-marble-top-dining-set-in-white-colour-by-durian-catherine-8-seater-marble-top-din-qdjhfy.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/c/a/800x880/catherine-8-seater-marble-top-dining-set-in-white-colour-by-durian-catherine-8-seater-marble-top-din-qdjhfy.jpg",
        image3:"https://ii1.pepperfry.com/media/catalog/product/c/a/800x880/catherine-8-seater-marble-top-dining-set-in-white-colour-by-durian-catherine-8-seater-marble-top-din-qdjhfy.jpg",
        image4:"https://ii1.pepperfry.com/media/catalog/product/c/a/800x880/catherine-8-seater-marble-top-dining-set-in-white-colour-by-durian-catherine-8-seater-marble-top-din-qdjhfy.jpg",
        price: " 349200",
        brand:"Durian",
        discount:"139680",
        discount_price :"209520",
    },
    {
        name: "Mariko 2 Seater Dining Set in Walnut Finish",
        subtype: "Modern 2 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/m/a/800x880/mariko-2-seater-dining-set-in-walnut-finish-by-mintwud-mariko-2-seater-dining-set-in-walnut-finish-b-qrqewb.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/m/a/800x880/mariko-two-seater-dining-set-in-walnut-finish-by-mintwud-mariko-two-seater-dining-set-in-walnut-fini-gd7k0l.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/m/a/800x880/mariko-two-seater-dining-set-in-walnut-finish-by-mintwud-mariko-two-seater-dining-set-in-walnut-fini-zvn7dm.jpg",
        price: " 17000",
        brand:"Mintwud",
        discount:"6501",
        discount_price :"10499",
    },
    {
        name: "Avian Solid Wood 2 Seater Dining Set In Provincial Teak Finish",
        subtype: "Contemporary 2 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/a/v/800x880/avian-solid-wood-2-seater-dining-set-in-provincial-teak-finish-by-woodsworth-avian-solid-wood-2-seat-c61e60.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/a/v/800x880/avian-solid-wood-two-seater-dining-set-in-provincial-teak-finish-by-woodsworth-avian-solid-wood-two--t0weao.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/a/v/800x880/avian-solid-wood-2-seater-dining-set-in-provincial-teak-finish-by-woodsworth--avian-solid-wood-2-sea-6qqrpa.jpg",
        price: "42999",
        brand:"Woodsworth",
        discount:"18393",
        discount_price :"24606",
    },
    {
        name: "Anitz Solid Wood 2 Seater Dining Set In Warm Walnut Finish",
        subtype: "Contemporary 2 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/a/n/800x880/anitz-solid-wood-two-seater-dining-set-in-warm-walnut-finish-by-woodsworth-anitz-solid-wood-two-seat-rdxmmy.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/a/n/800x880/anitz-solid-wood-two-seater-dining-set-in-warm-walnut-finish-by-woodsworth-anitz-solid-wood-two-seat-7hu9tk.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/a/n/800x880/anitz-solid-wood-two-seater-dining-set-in-warm-walnut-finish-by-woodsworth-anitz-solid-wood-two-seat-7i4aad.jpg",
        price: "47999",
        brand:"Woodsworth",
        discount:"17500",
        discount_price :"30499",
    },
    {
        name: "Drusilla Solid Wood 2 Seater Dining In Provincial Teak Finish",
        subtype: "Transitional 2 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/d/r/800x880/drusilla-solid-wood-2-seater-dining---in-provincial-teak-finish---by-woodsworth-drusilla-solid-wood--bml2va.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/d/r/800x880/drusilla-solid-wood-2-seater-dining---in-provincial-teak-finish---by-woodsworth-drusilla-solid-wood--bml2va.jpg",
        image3:"https://ii1.pepperfry.com/media/catalog/product/d/r/800x880/drusilla-solid-wood-2-seater-dining---in-provincial-teak-finish---by-woodsworth-drusilla-solid-wood--bml2va.jpg",
        image4:"https://ii1.pepperfry.com/media/catalog/product/d/r/800x880/drusilla-solid-wood-2-seater-dining---in-provincial-teak-finish---by-woodsworth-drusilla-solid-wood--bml2va.jpg",
        price: "25999",
        brand:"Woodsworth",
        discount:"10000",
        discount_price :"15999",
    },
    {
        name: "Harleston Solid Wood 2 Seater Dining Set In Honey Oak Finish",
        subtype: "Traditional 2 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/h/a/800x880/harleston-solid-wood-2-seater-dining-set-in-honey-oak-finish---amberville-by-pepperfry-harleston-sol-nv0uql.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/h/a/800x880/harleston-solid-wood-2-seater-dining-set-in-honey-oak-finish---amberville-by-pepperfry-harleston-sol-ljiwc3.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/h/a/800x880/harleston-solid-wood-2-seater-dining-set-in-honey-oak-finish---amberville-by-pepperfry-harleston-sol-dwruhx.jpg",
        price: "48999",
        brand:"Amberville",
        discount:"21143",
        discount_price :"27856",
    },
    {
        name: "Novo 6 Seater Dining Set In White Colour",
        subtype: "Industrial 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/n/o/800x880/novo-6-seater-dining-set-in-white-colour-by-bohemiana-novo-6-seater-dining-set-in-white-colour-by-bo-md7i1y.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/n/o/800x880/novo-six-seater-dining-set-in-white-colour-by-bohemiana-novo-six-seater-dining-set-in-white-colour-b-vfggsu.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/n/o/800x880/novo-six-seater-dining-set-in-white-colour-by-bohemiana-novo-six-seater-dining-set-in-white-colour-b-vvzdmb.jpg",
        price: "83999",
        brand:"Bohemiana",
        discount:"32000",
        discount_price :"51999",
    },
    {
        name: "Lomira Solid Wood 6 Seater Picnic Table With Benches In Distress Finish",
        subtype: "Industrial 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/l/o/800x880/lomira-solid-wood-6-seater-picnic-table-with-benches-in-distress-finish---bohemiana-by-pepperfry-lom-p8e8j4.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/l/o/800x880/lomira-solid-wood-six-seater-picnic-table-with-benches-in-distress-finish-by-bohemiana-lomira-solid--eyoqwq.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/l/o/800x880/lomira-solid-wood-6-seater-picnic-table-with-benches-in-distress-finish-by-bohemiana-lomira-solid-wo-hc8ozc.jpg",
        price: "48999",
        brand:"Amberville",
        discount:"21143",
        discount_price :"27856",
    },
    {
        name: "Fern 6 Seater Dining Set in Erin Brown Colour",
        subtype: "Transitional 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/f/e/800x880/fern-6-seater-dining-set-in-erin-brown-finish-by--home-fern-6-seater-dining-set-in-erin-brown-finish-twpuzx.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/f/e/800x880/fern-6-seater-dining-set-in-erin-brown-finish-by--home-fern-6-seater-dining-set-in-erin-brown-finish-dy93gs.jpg",
        image3:"https://ii1.pepperfry.com/images/vip_3d_view_icon.png",
        image4:"https://ii1.pepperfry.com/media/catalog/product/f/e/800x880/fern-6-seater-dining-set-in-erin-brown-finish-by--home-fern-6-seater-dining-set-in-erin-brown-finish-ophlhd.jpg",
        price: "42999",
        brand:"Woodsworth",
        discount:"18393",
        discount_price :"24606",
    },
    {
        name: "Daiton 6 Seater Dining Set in Expresso Finish",
        subtype: "Transitional 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/d/a/800x880/daiton-6-seater-dining-set-in-expresso-finish-by-hometown-daiton-6-seater-dining-set-in-expresso-fin-1yr5dp.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/d/a/800x880/daiton-six-seater-dining-set-with-bench-in-expresso-finish-by-hometown-daiton-six-seater-dining-set--qml0e0.jpg",
        image3:"https://ii1.pepperfry.com/media/catalog/product/d/a/800x880/daiton-six-seater-dining-set-with-bench-in-expresso-finish-by-hometown-daiton-six-seater-dining-set--nortya.jpg",
        image4:"https://ii1.pepperfry.com/media/catalog/product/d/a/800x880/daiton-six-seater-dining-set-with-bench-in-expresso-finish-by-hometown-daiton-six-seater-dining-set--8asjot.jpg",
        price: "78999",
        brand: "Mudramark",
        discount: "30500",
        discount_price :"48499",
    },
    {
        name: "Lawson 6 Seater Dining Set In Grey & Teak Finish",
        subtype: "Transitional 6 Seater Dining Sets",
        image1: "https://ii1.pepperfry.com/media/catalog/product/l/a/800x880/lawson-six-seater-dining-set-lawson-six-seater-dining-set-4gab3b.jpg",
        image2: "https://ii1.pepperfry.com/media/catalog/product/l/a/800x880/lawson-six-seater-dining-set-lawson-six-seater-dining-set-wrm0sn.jpg",
        image3:"https://ii1.pepperfry.com/media/catalog/product/l/a/800x880/lawson-six-seater-dining-set-lawson-six-seater-dining-set-trhseb.jpg",
        image4:"https://ii1.pepperfry.com/media/catalog/product/l/a/800x880/lawson-six-seater-dining-set-lawson-six-seater-dining-set-trhseb.jpg",
        price: "1815969",
        brand: "Fabuliv",
        discount: "94430",
        discount_price :"87166",
    },


    
]

